folder_in: /home/user2/tst/file
folder_out: /home/user2/tst/out
folder_ext: /home/user2/tst/ext
folder_badarx: /home/user2/tst/badarx
count_file: 5
size_file: 1M
type: zip
type_bad_arx: arx
local_path: /home/gb
remote_path: /home/user2
host: 0.0.0.0
user: user2

